# Generated by Django 4.2 on 2024-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('item_type', models.CharField(choices=[('WEAPON', 'Arma'), ('Shield', 'Escudo'), ('RING', 'Anel'), ('AMULET', 'Amuleto'), ('BOOTS', 'Botas'), ('HELMET', 'Capacete'), ('SHIELD', 'Escudo'), ('LEGGINGS', 'Calças'), ('CHESTPLATE', 'Peitoral'), ('NECKLACE', 'Colar')], max_length=150)),
                ('class_type', models.CharField(choices=[('KNIGHT', 'Guerreiro'), ('SORCERER', 'Feiticeiro'), ('DRUID', 'Druida'), ('PALADIN', 'Paladino')], max_length=150)),
            ],
        ),
    ]
